# Generated by Django 5.1.7 on 2025-03-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttemplate_templaterecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttemplate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_templates', to='payments.user'),
        ),
    ]
