# Generated by Django 5.1.7 on 2025-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymenttemplate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='templaterecipient',
            name='motive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
