# Generated by Django 5.1.7 on 2025-03-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_templaterecipient_motive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templaterecipient',
            name='motive',
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_groups', to='payments.user')),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='GroupRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motive', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='payments.recipientgroup')),
            ],
            options={
                'unique_together': {('group', 'phone_number', 'bank_code')},
            },
        ),
    ]
