# Generated by Django 5.1.7 on 2025-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_recipientgroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecipient',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouprecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
